### ISSUE TITLE
When I click bookmark link I see IE modal rather than Bootstrap modal

### ISSUE THREAD

**Issue by rvmpkgithub** [snikch/jquery.dirtyforms#105]
I am using Dirty forms along with bootstrap modal jQuery plugins.

When I make form dirty and clink links within the form/page and try ti leave the page then I do see nicer looking bootstrap modal.

But when I click link from bookmark and try to leave the page then I get default IE modal. 

I want to see Bootstrap modal to popup all the time.

Thank you.

**Comment by NightOwl888** [comment]
The browser manufacturers do not make this possible. All we can do from JavaScript is return a string to the browser through the [beforeunload event](https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload) when navigating away through the browser's navigation controls, and it is up to the manufacturer of the browser what to do with the string (including ignore it). We show a nice GUI dialog when a user clicks a link within the page, but any navigation that is not part of the page is not something that can be controlled via JavaScript.
