### ISSUE TITLE
Need same functionality on div click as it is on Anchor

### ISSUE THREAD

**Issue by sunnykantkr** [snikch/jquery.dirtyforms#109]
> I used jquery.dirtyforms with bootstrap modal to notify user that something is not saved in this page. This worked perfectly with anchor links. But, **I have a DIV on page which is actually working as a link to some other page. DIV has data-action attribute containing URL of the other page and on DIV click I am setting the data-action value to window.location.href to navigate.** When I clicked the DIV, it gave the confirmation message on default popup of browser instead of Bootstrap Modal.
> I have given a unique class to div as tabDiv. I tried to add the support for DIV in Jquery.dirtyforms.js and witten this which did not work....thanks for the help :

```
var events = {
        bind: function (window, document, data) {
            $(window).bind('beforeunload', data, events.onBeforeUnload);
            $(document).on('click', 'a:not([target="_blank"])', data, events.onAnchorClick)
                       .on('submit', 'form', data, events.onSubmit)
                       .on('click', 'div.tabDiv', data, events.onDivCLick);
        },
       onDivCLick: function(ev){
             bindFn(ev);
        },
```

**Comment by NightOwl888** [comment]
Already answered in [this answer](https://github.com/snikch/jquery.dirtyforms/issues/104#issuecomment-225385989). [This answer](http://stackoverflow.com/a/37619502/181087) and [this answer](https://github.com/snikch/jquery.dirtyforms/issues/103#issuecomment-212747076) may also be helpful.
