### ISSUE TITLE
2.0.0-beta00005 to 2.0.0 breaking change - add ignoreSelector: a:not([href]) >

### ISSUE THREAD

**Issue by ToreOlavKristiansen** [snikch/jquery.dirtyforms#113]
Hi.

To ignore also children of anchor tags without href:
`ignoreSelector: "a:not([href]), a:not([href]) >"`

Example: using FontAwsome i-tag inside anchor.

Please consider updating documentation.

Best regards,
Tore.

**Comment by NightOwl888** [comment]
Thanks. I updated the documentation.
