### ISSUE TITLE
Changed form not caught

### ISSUE THREAD

**Issue by lcsqlpete** [snikch/jquery.dirtyforms#116]
I'm by no means a javascript expert so I suspect I'm doing something wrong but I can't get the dirtyForms plugin to work.

javascript:
`$(document).ready(function () {
    
    $('form.watchChanges').dirtyForms();
    
});`

html form definition:
`<form class="form-horizontal watchChanges" action="xyz.php method="post" style="margin-left:10px;margin-right:10px">`

html script defs at the end of tbody:
`<script src="assets/js/jquery.min.js"></script>
        <script src="assets/bootstrap/js/bootstrap.min.js"></script>
        <script src="assets/js/jquery.dirtyforms.js"></script>
        <script src="assets/js/jquery.dirtyforms.dialogs.bootstrap.js"></script>
        <script src="assets/js/lcsql-jslib.js?v=1"</script>`

The lcsql-jslib file contains the javascript above.

html for the close window button:
`<a href='https://ke.haworths.org/Hospitals.html' class="btn btn-default btn-sm ke-grey-bg" role="button" data-toggle="tooltip" title="Close this window"> 
    <i class="material-icons">close</i>
</a>`

I enter new data into any of the form input controls then click the close window button, I go straight back to the Hospitals.html page, no dialog from dirtyForms.

Any help much appreciated.

Pete

**Comment by NightOwl888** [comment]
If you have copied and pasted the code, there are a couple of typos:

```
<form class="form-horizontal watchChanges" action="xyz.php method="post" style="margin-left:10px;margin-right:10px">

is missing the " after xyz.php - it should be:

<form class="form-horizontal watchChanges" action="xyz.php" method="post" style="margin-left:10px;margin-right:10px">

```

```
<script src="assets/js/lcsql-jslib.js?v=1"</script>

should be:

<script src="assets/js/lcsql-jslib.js?v=1"></script>
```

I suspect the latter may be causing all of your JavaScript code to fail (including Dirty Forms).

If that doesn't solve your issue, please make a standalone HTML page exhibiting the problem and describe what is "not working" and how to reproduce the broken behavior. Post the contents of the page here, and use the [CDN references](https://github.com/snikch/jquery.dirtyforms#cdn) so it will execute on my end the same as it executes on yours.

**Comment by lcsqlpete** [comment]
Thanks for the quick response.  The form definition was a typo in my posy.  I changed the script statement as you suggested and all is now working.  Thanks for your help.
Pete
