### ISSUE TITLE
Not marking as dirty if autofocused element is changed

### ISSUE THREAD

**Issue by jk3us** [snikch/jquery.dirtyforms#50]
I have a form (loaded via ajax, not sure if that is related) where I auto-focus the first field.  If I type something in that field, the reload the page, it doesn't get flagged as dirty.  If I click out of and into that field and change it it's fine.  Likewise, if I tab to the next field, ctrl+tab back and type something it gets marked as dirty.

**Comment by marceltschoppch** [comment]
Added pull request #73 to fix this problem.
