### ISSUE TITLE
DirtyForms ignored hidden fields

### ISSUE THREAD

**Issue by calciphus** [snikch/jquery.dirtyforms#53]
I'm trying to use DirtyForms to catch when a user has changed elements in a form in a modal window. However, some of those elements are custom Bootstrap-style dropdown menus (because the client didn't like default select fields), which change a hidden field.

When jQuery changes the value of a hidden field, $.DirtyForms.isDirty() still returns false. Any thoughts on how to fix this?

**Comment by mgroves** [comment]
If you trigger the change event on hidden fields, then dirtyforms will pick it up.

If you check out the init function, you'll see that inputSelector will include hidden inputs, but needs a focus or change event to actually trigger.

**Comment by NightOwl888** [comment]
As @mgroves pointed out, you can trigger the events manually to make Dirty Forms pick it up, which is probably your simplest option.

Alternatively, you could implement a [custom helper](https://github.com/snikch/jquery.dirtyforms#custom-helpers) that reads the state (from a custom piece of data you add) from the hidden fields. This will give you the added advantage of being able to "undo" the dirty state when the user undoes their edits to each widget. See [Setting a Form Dirty Manually](https://github.com/snikch/jquery.dirtyforms#setting-a-form-dirty-manually) for more information.
