### ISSUE TITLE
navigating jquery UI timepicker pop-up / iOS / touch punch - triggers dirty dialog

### ISSUE THREAD

**Issue by bkwdesign** [snikch/jquery.dirtyforms#57]
Yeah, ridiculous for me to even post this, perhaps.. but.. figured I'd throw it up here.

I'm using 'touch punch' so that iOS touch events will work with my jQuery UI widgets.
Seems to be working pretty good.

So, I have this jquery UI timepicker, and when I try to navigate through the calendar (specifically use the arrow buttons in the corners of the pop-up to change months), it must be interpreting falsely somehow that I'm leaving the page. The "are you sure you want to leave" dialog pops up. 

The timepicker, to my best knowledge, performs no under-the-hood ajax / xhr requests and furthermore works flawlessly in other browsers I'm testing. If I get time, I'll see if I can post a jsfiddle that you would have to try on an iPad or some such...

**Comment by NightOwl888** [comment]
By default dirty forms interprets a click on any anchor tag with an href attribute (`'a[href]'`) as an attempt to navigate away from the page. You can avoid this in UI addons such as a datepicker by using jQuery to add the `ignoreClass` to any anchor tags that it uses to work with the addon.

```js
$('a.third-party-non-navigating-anchor').addClass($.DirtyForms.ignoreClass);
```

Then it will ignore the clicks from those anchors.

**Comment by NightOwl888** [comment]
There is now a section called [ignoring things](https://github.com/snikch/jquery.dirtyforms#ignoring-things) in the documentation that outlines all of the different ways you can ignore interaction with elements outside of Dirty Forms. That should easily cover both of these scenarios. 

But as I mentioned previously, the [default anchor behavior](https://github.com/snikch/jquery.dirtyforms#default-anchor-ignoring-behavior) assumes that any anchor click (whether from a 3rd party plugin or not) is an attempt to leave the page. You must manually ignore any anchors that are used for other purposes either by adding them to the `ignoreSelector`, adding your widget to an HTML element with the `ignoreClass` on it, or setting the `ignoreClass` directly to the anchor elements that are to be ignored by Dirty Forms.
