### ISSUE TITLE
Using pnotify for dialog with dirtyforms

### ISSUE THREAD

**Issue by aluck1** [snikch/jquery.dirtyforms#58]
I'm sharing my dialog section to get dirtyforms to work with pnotify.  This creates a modal-confirmation notification.

dialog : {
				refire : function(content, ev){
					return false;
				},
				fire : function(message, title){
					var content = {title: title, 
									hide: false,
									text:'<p>' + message + '</p><span style="display:block; text-align:center;"><button type="button" class="ignoredirty continuedirty">Continue</button><button type="button" class="ignoredirty button canceldirty">Stop</button></span>',
									before_open: function(pnotify) {
										/* Make a modal screen overlay.*/
										if (typeof modal_overlay != "undefined") modal_overlay.fadeIn("fast");
										else modal_overlay = $("<div id='ui-widget-overlay'/>")
											.addClass("ui-widget-overlay")
											.css( {
												"display": "none",
												"position": "fixed",
												"top": "0",
												"bottom": "0",
												"right": "0",
												"left": "0"
											})
											.appendTo("body").fadeIn("fast");
									},
									before_close: function(e) {
										modal_overlay.fadeOut("fast");
										//$.DirtyForms.choiceCommit(e);
									}};
					var notice = $.pnotify(content);
				},
				bind : function(){
					$('.canceldirty, .ui-pnotify-container, #ui-widget-overlay').click($.DirtyForms.decidingCancel);
					$('.continuedirty').click($.DirtyForms.decidingContinue);   
				},
				stash : function(){ 
					return false;
				},
				selector : '#ui-pnotify'
			},

**Comment by NightOwl888** [comment]
Thanks for the info. I created a [pre-fabricated PNotify package](https://github.com/NightOwl888/jquery.dirtyforms.dialogs.pnotify.dist) with the Dirty Forms 2.0 release, but it is compatible with any version 1.0 or greater.

If you find any issues with it, be sure to let me know. Thanks.
