### ISSUE TITLE
alert box shown when nothing changes are done in form

### ISSUE THREAD

**Issue by adityapal007** [snikch/jquery.dirtyforms#60]
please tell me what to do with this issues when nothing changes is being done in form on which this plugin used and when user exits form it still shows alert box of unsaved changes .so please tell me how to fix this issue so that its alert box only apears when change is being done in the forms.

**Comment by NightOwl888** [comment]
Could you post an example? DirtyForms is not designed to show an alert unless a change is made to the field, so this may either be a bug or a misconfiguration on your part.

**Comment by NightOwl888** [comment]
No response in over 2 months. I am closing this issue. If you are using the [always dirty helper](https://github.com/NightOwl888/jquery.dirtyforms.helpers.alwaysdirty.dist#readme), this is normal and expected behavior.
