### ISSUE TITLE
Disable dirtyForms

### ISSUE THREAD

**Issue by alrick** [snikch/jquery.dirtyforms#61]
Hi there!

Great plugin.
I was wondering if there is a way to disable dirtyforms after setting it.
If I set it with `$('form').dirtyForms();` can I then remove it from `$('form')`?

Thanks

**Comment by NightOwl888** [comment]
FYI - Dirty Forms 2.0 BETA is now available. The `$.DirtyForms.disable()` method has been removed. You can now use the `$.DirtyForms.ignoreClass` to disable entire container elements. To disable Dirty Forms completely, just put it onto the `html` or `body` element.

```javascript
$('html').addClass($.DirtyForms.ignoreClass);
```

Please give it a try and report any issues you find. Thanks.
