### ISSUE TITLE
ignoreClass not working correctly

### ISSUE THREAD

**Issue by jhermiz** [snikch/jquery.dirtyforms#63]
See this: http://stackoverflow.com/questions/23679317/how-can-i-exclude-controls-from-making-form-dirty?noredirect=1#comment36380165_23679317

What I tried doing is adding some class names to my various controls so that they do not make my form dirty.  class='ignoreDirty' and then I do the following:

$('form').dirtyForms({ 	ignoreClass : "ignoreDirty" });

However, this doesnt seem to work.  After selecting my drop down whose class is ignoreDirty it raises the message that the form is dirty and I need to save changes.  This filter does post back but that should not matter.  See stackoverflow post for more info.

**Comment by NightOwl888** [comment]
Fix already implemented.
