### ISSUE TITLE
jQuery.DirtyForm - Usage with iFrame

### ISSUE THREAD

**Issue by srikanthnd** [snikch/jquery.dirtyforms#68]
Hi,

can you provide an example of how to detected dirty fields within an iFrame or in general using jquery.DirtyForm within iFrames.  While googling, I did come across one of the stackoverflow questions http://stackoverflow.com/questions/155739/detecting-unsaved-changes which was answered by NightOwl888, in which it was mentioned that the plugin supports iFrame.  However, with my limited knowledge of the plugin, I am unable to get it working while using within the iframe.

Regards,
Srikanth Naropanth

**Comment by NightOwl888** [comment]
I know this is probably too late, but I created a [demo Gist](https://gist.github.com/NightOwl888/035788394a54c0400416) showing the usage of dirtyForms within an IFrame. Basically, it is set up to stop the browser of the page that the IFrame is on when the page within the IFrame is dirty. dirtyForms must be on the form that is in the IFrame in order for it to work.

For the page that is hosting the IFrame, it doesn't matter whether or not dirtyForms is on it or not. You could potentially put it there as well, but it would mean that all of the forms inside of the IFrame may not be dirty if you expect the form with the IFrame to be submitted.

Neither @snikch nor I contributed this functionality, so I am not sure exactly what use case it was designed for. This demo is similar to the tests that I ran when I refactored the code so as not to use the livequery library or the jQuery live method (which has been deprecated). I ran a quick test and it seems that none of the forms in the page that is hosting the IFrame are allowed to be submitted when the a form within the IFrame is dirty. The only use case that would make sense is to use AJAX to submit that other form in the IFrame host page so as not to reload the entire page including the IFrame, but it is not a use case I have tested.

**Comment by NightOwl888** [comment]
FYI - Dirty Forms 2.0 BETA is now available. The "IFrame support" (which really only covered a specific use case) has been replaced with customizable event binding, which should cover any use case with IFrames, and a lot more.

Please give it a try and report any issues you find. Thanks.
