### ISSUE TITLE
Formalize the Release Process and Versioning

### ISSUE THREAD

**Issue by NightOwl888** [snikch/jquery.dirtyforms#72]
Its been some time since I have worked on this project and I would like to make it more accessible for my own personal use. First and foremost, I would like to make it into a NuGet package (or actually, a set of packages - one for the main package and one for each plugin) on the NuGet Gallery for easy usage with Visual Studio projects. However, I also would like to have it available as a set of minified files on a CDN for the production environment.

Build Environment
==

Both of these require a formal versioning process and release process, which is probably long overdue for this project. But formal versioning requires a single source of truth so I want to make sure the decisions about how to proceed are yours. My goal isn't to rip control of this project out of your hands, but to make it more accessible to everyone (whether or not I get your cooperation) and to make the build process as simple as possible.

I have worked on a couple of other open source projects and in particular did some work on the build scripts. Both of those were done in Windows PowerShell using the [PSake build automation tool](https://github.com/psake/psake/wiki), but I also have some experience with MSBuild and Windows `.bat` files. I have also tinkered with Maven a little, but not too seriously. I am just trying to get some general idea what the feeling is about tying the build process to the Windows platform because (as far as I know) NuGet only builds on Windows, and also I believe that most other release formats can also build on Windows. But then, there is probably a way to remotely run the NuGet process via MyGet URL so any platform will probably do. If Windows PowerShell is not a preferred way to build, is there any particular preference?

Also, there might be other formats that the community wants to see this plugin available in, and I would like for people to weigh in and send the appropriate documentation so those formats can be part of the build.

Thoughts?

Continuous Integration
==

Both of the other projects I worked on used a very simple free CI server called [MyGet](https://www.myget.org/) in order to automate the version numbering, build the deployment (NuGet) packages, and to tag the Git repository with the version number. This also makes it easy to put release notes under the [releases tab](https://github.com/snikch/jquery.dirtyforms/releases) after the build is complete to summarize the changes. For this project, it also makes it possible to automate the minification process via command line.

Of course there are also full blown CI servers available for open source usage as well as other specialized services like that one. Do you have a preference on which CI server to use?

If you are fine with MyGet, then please [sign up for a free account](https://www.myget.org/Account/Login?ReturnUrl=%2fSubscription%2fSignUp%2fMG001%3futm_source%3dmyget%26utm_medium%3dweb%26utm_campaign%3dfrontpage-plan-MG001&utm_source=myget&utm_medium=web&utm_campaign=frontpage-plan-MG001) and give me your user name so I can setup the permissions for you to build. If not, please state your preferred CI environment so I can sign up for that one and read the docs.

Versioning
==

I cast my vote for using [Semantic Versioning](http://semver.org/), which is the same scheme that pretty much every jQuery plugin uses.

Of course, Semantic Versioning complicates things a little - we need to ensure the public API has no breaking changes or the major version number must increase. So pull requests need to be checked against these rules in order to do a triage on what can be released in a patch, minor, or major version. It might be best to come up with some formalized branch naming prefix scheme as well as some tags to put on the pull requests indicating which ones should go in which type of release. Basically, if we don't reign in control of the changes, the version number will grow exponentially.

Also, since this project has been in the works for several years and is technically "production ready" (at least as far as I know), do you have any thoughts on what version number to call the first official release?

CDN Provider(s)
==

A quick search came up with [jsdelivr](http://www.jsdelivr.com/) and [cdnjs](https://cdnjs.com/) as being free open source CDN servers. They receive their updates as Git pull requests, so it is possible to partially automate the release in the build. If you like this idea, please create an official fork of the repos and give me access to them so I can have the build server push the commit with the release in it to the fork.

If you have any other ideas or preferences of CDN hosting, let me know.

NuGet Gallery
==

Also, so your name is on the official NuGet release please [sign up for an account](https://www.nuget.org/users/account/LogOn?returnUrl=%2F) there so I can make you an owner of the official feed, and let me know the username.

File and Directory Names
==

The way most jQuery plugins version is to put the version number on the folder name and keep the file name consistent from one version to the next. However, others (such as jQuery) make the version number part of the actual file name. Personally, I like the versioned folder option.

Also, this is the way I am thinking that file names should be done.

| File  | File Names |
| ------------- | ------------- |
| Main Package | `jquery.dirtyforms.min.js`  |
| Main Package Uncompressed | `jquery.dirtyforms.js`  |
| Plugin Package  | `jquery.dirtyforms.plugin.<pluginname>.min.js`  |
| Plugin Package Uncompressed  | `jquery.dirtyforms.plugin.<pluginname>.js`  |

Let me know whether or not this suits you.

Minification/Compression
==

My plan is to use the [.NET port of Yahoo YUICompressor](https://github.com/PureKrome/YUICompressor.NET) and the MSBuild task to run it from the command line. It works the same way as the [Java version](http://yui.github.io/yuicompressor/), and both basically have the same number of dependencies.

Final Thoughts
==

I know this post is a bit long, but don't let it overwhelm you. I have done this before so I know that there isn't a lot of work involved. Most (if not all) of this can be accomplished in a single weekend.

One thing I didn't touch on was testing - there are JS frameworks to automate the testing (such as [jsunit](http://www.jsunit.net/)) rather than having a custom test harness. I have read about them, but never used them. I notice it is possible to [run these tests from the command line](https://grails.org/wiki/jsUnit%20plugin), so they could also be part of the build process. I don't want to make the build process too lofty of a goal, but unit testing this framework could make it easier to maintain and less dangerous to receive contributions to it. Which, in turn would help with ensuring backward compatibility for Semantic Versioning. Just a thought.

Anyway, I would like to start working on the build script so I can at least get the versioning, minification and NuGet packaging done for my personal use. Just let me know if PowerShell and PSake sounds reasonable to you ASAP so I don't have to redouble my efforts and build a completely different script for the official pull request.

**Comment by NightOwl888** [comment]
@snikch 

I would appreciate it if you could at least make me a collaborator so I can help you manage issues. I noticed that there are several that are open that have already been resolved.

In addition, getting this up on a CDN is kind of a priority for me. It would really help a lot when it comes to writing demos because currently there is no public location to reference this plugin from. The automation isn't something that needs to be done right away, but we should at least make an effort to agree on a version number and submit to the CDN providers above manually. I would appreciate if you would create the official forks at [jsdelivr](http://www.jsdelivr.com/) and [cdnjs](https://cdnjs.com/) so they have your user name in them.

**Comment by snikch** [comment]
Hey @NightOwl888, thanks for your time on this!

I'd be happy to make you a collaborator so you can make the project more accessible, that's great!

# Build
For a build tool, the general consensus in the JavaScript community is to use Gulp. This is an npm package, is cross platform and is suitable for the task. Using a Windows specific tool would limit accessibility to a lot of people (myself included).

# CI

I'd prefer to use Travis, as this is where most OS JavaScript libraries are hosted. I highly recommend it. I believe it does all that you require, but if that's not the case then I'm not too worried.

# Semver

:+1: 

# CDN

:+1: Either is fine with me.

# Nuget

I've signed up with username: snikch

# Filenames

:+1: 

# Minification

:+1:

**Comment by NightOwl888** [comment]
## Build & CI & Minification

I have no problem with using Gulp or Travis CI, and I certainly wouldn't mind expanding my skill set. My only issue is that of the amount of time to set it up, which admittedly is currently unknown.

I went through the documentation for both and also set up a Travis CI account, and although it looks somewhat simple, but my experience with a full-blown CI setup (TeamCity) is that working out exactly what command-lines to run (and how to pass options to them using the scripting technology), how to get the version to increment and read it from the build script, setup the repo labeling, etc. is the most time consuming part.

With MyGet/PSake I could for the most part copy and paste and have the whole thing running in a matter of 2-3 hours including auto-incrementing the version number, versioning for pre-release builds, and labeling the Git repo. With the learning curve of these new tools it will clearly take much longer than that. It would help considerably if you set up the CI environment and build a basic skeleton Gulp script showing how to read the version number from the CI and run a basic command line tool.

For the command line tool, I have a new suggestion for the minification (based on this new environment and cdnjs's suggestion), [UglifyJS2](https://github.com/mishoo/UglifyJS2).

It looks like there is an [Gulp solution](https://github.com/mckn/gulp-nuget) for NuGet packaging and publishing. So it looks like we're covered there.

Even if MyGet isn't used as a build server, it can still host a feed that can be used as a staging area to test installing the packages and to work out any issues before making the package live on NuGet Gallery (which is not something that can be undone). So, I still suggest you [sign up for an account there](https://www.myget.org/Account/Login?ReturnUrl=%2fSubscription%2fSignUp%2fMG001%3futm_source%3dmyget%26utm_medium%3dweb%26utm_campaign%3dfrontpage-plan-MG001&utm_source=myget&utm_medium=web&utm_campaign=frontpage-plan-MG001) and send me your user name.

> Note: I acknowledge you have already signed up for NuGet Gallery, but I won't be able to give you permission to the feed there until after it is created (by pushing the first version).

## CDN

Actually, I was thinking both (and others if we can find free ones for open source). 

All we need are fork of the repo (with collaborator access to me) of jsdeliver:
https://github.com/jsdelivr/jsdelivr

And it looks like cdnjs has a [command line tool for the release](https://github.com/cdnjs/cdnjs#adding-a-new-or-updating-an-existing-library) and they automatically check for updates via a JSON configuration file, so I guess we don't need a fork of that one.

For jsdelivr, it is possible to [automate pull requests via command line](http://stackoverflow.com/questions/15302570/automatically-open-a-pull-request-on-github-by-command-line) - so looks like the whole thing can be automated.

## Versioning & API

The highest priority is to get the API ready for release, since for the first release the build and pushing could potentially be done manually before the build process is ready for prime time. This means several things, but the main issue is to ensure the API is not very likely to require breaking changes after the release to conform with SemVer. I got burned by skipping this step on another project, I don't want to get burned again :).

### API

I noticed that someone contributed a "disable" option. Unfortunately, this is less than ideal because 1) disable = "false" is a double negative, and in my opinion it is confusing, 2) the option is global - there is no way to turn it on or off per form, and 3) there is no corresponding "enable" function to re-enable dirtyForms. So it would seem that refactoring this functionality would be high priority to ensure if any breaking changes are required to make these fixes are introduced prior to the first release.

The default set of [input, selection, and reset selectors](https://github.com/snikch/jquery.dirtyforms/blob/master/jquery.dirtyforms.js#L105) that are used should be made public properties so people can change them easily from the outside of the plugin. The same goes for the [exit bound selectors](https://github.com/snikch/jquery.dirtyforms/blob/master/jquery.dirtyforms.js#L284).

It seems as though the default dialog should be the browser dialog rather than FaceBox. And we could have individual JavaScript files that could be used as separate add-on packages for the most common dialog frameworks, which could then be made into separate NuGet packages, making it easy to plug in the dialog functionality in an automated way.

Also, I mentioned testing before. Although we don't have to make the tests (yet) for the API, it is important to make sure it is "testable". Upon review I noticed that most of the functionality is in private methods, which obviously can't be tested from the outside. That said, it is best that these members are not polluting the global function space.

2 possible ways to remedy this:

1. Create a public function that can be used to call private functions from the outside for testing purposes.
2. Move all of these private methods into a public object of their own with public accessibility.

I am leaning toward the second option, but if you know of any pitfalls with this and/or have any other ideas, please mention them.

Of course, it might help to set up a few tests to better gauge what types of other things are untestable (or if you already know of any potential problems with testing the current code using a JavaScript testing framework, please do tell).

> I will get started on the API fixes as soon as I get the chance (and your stamp of approval).

### Contributing

To ensure that we get future patches that conform to SemVer, we should have a CONTRIBUTING.md file that outlines our guidelines. I would appreciate if you would make the first draft with the things you feel are important (coding style, comments, documentation, branch naming, pull request procedure, etc.) A couple of things to read (and include links to in the document) are [Don't "Push" Your Pull Requests](http://www.igvita.com/2011/12/19/dont-push-your-pull-requests/) and [Open Source Contribution Etiquette](http://tirania.org/blog/archive/2010/Dec-31.html).

It is important that we state that features with documentation/tests will be considered for inclusion with higher priority than those without these things, since we will likely have to add those ourselves. Since we don't yet have anything other than a manual test harness, the testing part can be omitted for now, but I think we should be more serious about how documentation is provided and presented going forward.

### Documentation

One requirement of SemVer is that the whole public API be documented. I took care to document the entire API before in the readme file, but I see that some contributions were made since that are not documented.

Of course, having the documentation all in the readme file is not ideal. It would be a better experience to have jQuery style API documentation, ideally complete with demos. It seems there are a few options for automating that process.

1. [jsdoc 3](https://github.com/jsdoc3/jsdoc) (or [jsdoc 2](https://code.google.com/p/jsdoc-toolkit/)) - This one looks like it has the most compatible tooling. However, I don't see an option to use documentation from external files (it reads from the comments), jsdoc 2 is on the soon-to-be-retired Google Code, and jsdoc 3 is currently in beta.
2. [Natural Docs](http://www.naturaldocs.org/) allows you to document the code in external files or comments.

It is unclear whether it is possible to make on-page demos using either of these technologies, but it is a start at least. Do you prefer inline documentation in comments, or external documentation? Or do you know of another technology that could do this task better?

And of course a related issue is - where to host the documentation?

I guess we could still consider this an alternative to what we have now, but I think that Dirty Forms is difficult to use with the existing documentation alone (in a recent project I found myself looking into the source code and at samples that I used before for testing purposes moreso than the docs), especially when you want to change/disable the default dialog.

### Version Number

Should the first "official" release be 1.0?

**Comment by snikch** [comment]
I should probably be clear about how much input I'm able to provide to this library at the moment. My ability to commit time is pretty much 0 due to pressures from other areas of my life. You seem like a pretty onto it guy, so I'm happy for you to take this in your own direction as you see fit, you don't need to wait for my approval on these decisions - anything you decide is better than what there is currently :)

:shipit:

**Comment by NightOwl888** [comment]
Alright, thanks. To be honest, I don't have a lot of time to dedicate either, but I am finally able to make use of this library after committing some work to it 3 years ago, and I would really like to see it on a CDN where it will be more useful.

I was able to get Gulp up and running pretty quickly, and already have it compressing the main js file and packaging it with NuGet. You are right - this is a better tool than Windows Powershell. The only thing I don't like is having to fetch new packages for every little thing I want to do, but since it is automated it isn't that hard.

I also discovered [this doc](http://www.mikeobrien.net/blog/using-gulp-to-build-and-deploy-dotnet-apps-on-windows/#gulp-build-server) that pretty much explains it all in Windows/.NET terminology including the most common tasks for CI.

**Comment by NightOwl888** [comment]
Ok, switching to streamlined requests to minimize the amount of time you will need to read and respond to them. I need your help to set some of this stuff up because of permission issues.

1. Please enable [Travis CI](https://travis-ci.org/) on this repo (I have no permission to do this)
2. Please fork [cdnjs](https://github.com/cdnjs/cdnjs) and give me collaborator access. They do not accept submissions from non-official sources.
3. Please sign up for [MyGet](https://www.myget.org/Account/Register?ReturnUrl=https%3A%2F%2Fwww.myget.org%2Faccount%2Flogin) and send me your user name. It will be better in the long term if you have permission to manage the NuGet feed.

I am considering using MyGet for the release process, since Travis CI doesn't seem to have versioning built in. Travis CI will still be useful for commit-driven and pull request driven linting and testing, though.

**Comment by NightOwl888** [comment]
@snikch 

I made [some progress](https://github.com/NightOwl888/jquery.dirtyforms/tree/master) on this - namely I have a working build script that executes on MyGet and creates both NuGet and bower releases (bower through git submodules using [this approach](http://blog.stackfull.com/2013/05/publishing-bower-components/)). 

MyGet is simply the best option for releasing because it means no API key (which must be kept private) will need to be passed as an argument to the build script. I still think that TravisCI fits into the picture, but it won't really matter much until this project has unit tests (and you enable TravisCI on this repo, because I don't have permission to).

Question
==

Is there some customization to [facebox](https://github.com/snikch/facebox) that you did to make it into its own fork? I noticed that there is a pull request added to it that doesn't exist in the original, but then this one is now 12 commits behind the original.

The reason I ask is because this is a dependency of the default configuration, and I will need to package it up in NuGet in order to make it a dependency on this package (and eventually the same thing applies to NPM).

The main project hasn't had any activity for 2 years, and has 29 open pull requests. I think the best approach would be to get the latest updates from the main branch that have been officially accepted and then release an "unofficial" version 1.4.0 (since 1.3 is the last official one and there are some updates since then).

I would appreciate if you could provide me collaborator access on your fork and your advice about how to proceed with versioning and releasing facebox, as I have no personal interest in using it. Should we make a DirtyForms-specific version (by giving it a name with a dirtyforms suffix), or make a general one?

> Note that I plan to do an "official" 1.0 release, since there is already an unofficial one on bower, and I will need to have that one replaced. I will temporarily change the code back to the point in time it was released, re-release, and then revert the commit in order to do a 1.1 release. I also plan on making a 2.0 release that removes the direct dependency on facebox by changing the default to using **no** dialog and moving it into its own "dialog" module (which will still depend on facebox).

**Comment by snikch** [comment]
Hey - that's great news!

I have no memory of why I created a facebox fork. I appear to have added one commit [2ab942a50e](https://github.com/snikch/facebox/commit/2ab942a50e942bf9b797cce17bb5df3e2bb11726). I'll add you as a collaborator now.

**Comment by NightOwl888** [comment]
> It might be best to completely remove the facebox dependency, and have a simple documented example of how to use it. Ideally the library would come with a 'default' implementation so people can just drop it in, but that needs to be appropriate for the current market, not the market that existed 4-5 years ago when I wrote this.

Agreed. But as I mentioned this would be a breaking change, thus will require a 2.0 release. My focus right now is to re-release this as 1.0.0, and then patch some of the bugs bringing it to 1.1.

Moving the dependency to a `jquery.dirtyforms.dialogs.facebox` module is the best solution (for 2.0), but it still will require facebox to be packaged up so it can be a dependency in each respective environment. Note that CDNJS has a URL scheme for concatenating files and most build environments have some kind of bundling tool, so it would be best to do it this way to ensure the end user has all of the dependencies and let them worry about minimizing requests to the server after the fact.

Your Assistance Needed
==

I need you to complete a few tasks that I don't have permission to do.

1. Change the default branch of [snikch/facebox](https://github.com/snikch/facebox) to master.
2. Enable issue tracking in snikch/facebox (I am watching the repo and will help you out with any requests that come in).
3. Log into MyGet and add your username/password for GitHub to the 2 feeds/builds.
4. (Optional) Enable TravisCI on both repo (facebox and dirtyforms). I still think it would be a good idea to use its feature that does testing on pull requests (at least to do JS lint).

For step 3, do the following

1. Login to https://www.myget.org/
2. Select the jquery-facebox feed
3. Click on Build Services
4. For the snikch/facebox source, click the edit button (the little pen icon)
5. In the popup, scroll down to Authentication and type your **GitHub** username and password
6. Scroll to the bottom and click on the save button (you may need to maximize your browser window in order to see the button).
7. Repeat steps 2-6 for the jquery-dirtyforms feed

Note that after you provide credentials, the jquery-facebox feed should build (by clicking the play button) and should create both a NuGet and NPM package in the feed, as well as commit the version number and tag the [facebox distribution repo](https://github.com/NightOwl888/jquery.facebox.dist) for Bower. Don't overdo it though, I want to try to keep this from mucking up the live repo with commits and tags (I have already done some testing).

Presently, the jquery.dirtyforms repo is not set up with a build script, so the build will fail if you attempt the above on the corresponding feed.

Do note that I plan on documenting the release process as well, but it really isn't much more complicated than this (Bower and CDNJS are completely automated, NuGet and NPM require a few more button clicks each).

Also note that I plan to send a pull request to the main facebox repo so they can manage the release process, but I am not going to hold my breath that it will ever be done.

New Logo
==

![dirty-forms-logo](https://cloud.githubusercontent.com/assets/1538288/8163044/f83fe40c-13aa-11e5-809a-cbd2a0cfe169.png)

NuGet has space for a square icon to help identify packages, so I created one to make it stand out. I also plan on putting this on the readme file.

**Comment by NightOwl888** [comment]
@snikch 

I am pretty much ready to make a go of the release (Bower, NPM, MyGet, and JSDelivr CDN).

I changed my mind about burdening you with facebox and decided to take it under my own wing and  do the release myself on my own fork. Therefore, you might get some messages about having your access removed from the repo and feed for facebox.

However, I still would like to use this repo as the "main" development repo for dirty forms. I can release without your help, but I cannot create a **release process** that anyone can use without your help. Rather than passing around secrets such as API keys, MyGet will impersonate your GitHub credentials (required because of GitHub's lame security setup) so that anyone with access to MyGet can follow the steps to release.

Currently, I have to build against my own copy of the repo and then push the commits and tags created by the build back into your repo. Possible. But not ideal. Nobody else but me will be able to do it.

So please follow the steps in my last message to add your credentials to the MyGet dirty forms feed. It will only take about 2 minutes. Your credentials are stored securely on MyGet and I won't have access to them (nor anyone else).

For the sake of completeness, there are 2 alternative options than doing the above:

1. I could manage the release process entirely myself (without being able to permit anyone else to do it)
2. You could [transfer ownership of this repo](https://help.github.com/articles/transferring-a-repository/) to me

The first option is a PITA because it means keeping your fork and my fork in sync all the time, and essentially nobody else will be able to do it unless you give them collaborator access and they are proficient enough with Git and MyGet to pull it off. Not to mention, it is prone to human error because each person who builds will have to ensure that the version number is incremented sequentially manually.

The second option is something to consider, but it will likely break lots of URLs. I believe I will need to delete my fork of this repo in order to do it, so give me a head up if that is your decision. It will confuse people, but it is workable. If you go this route I will most certainly give you collaborator access so you can develop on it if you find the time.

But of course, the simplest route (and least time consuming) is to simply enter your credentials into the MyGet build so I can manage everything for you, including documenting the release procedure and giving others access to it if they need it.

1. Login to https://www.myget.org/
2. Select the jquery-dirtyforms feed
3. Click on Build Services
4. For the snikch/jquery.dirtyforms source, click the edit button (the little pen icon)
5. In the popup, scroll down to Authentication and type your GitHub username and password
6. Scroll to the bottom and click on the save button (you may need to maximize your browser window in order to see the button).
7. Let me know when complete.

**Comment by snikch** [comment]
Hey Shad, thanks for all of this. I've created an account at MyGet, but don't see any feeds - such as the dirtyforms one.

At this point I'm wondering if it will just be easier to transfer ownership to you. I believe that GitHub redirects all the links, so that's not a problem.

**Comment by snikch** [comment]
I'm surprised that MyGet only allow authentication via Github credentials. It's pretty much a show stopper for me. My Github account is pretty much the key to several kingdoms (or startups, whatever you want to call them) and I just cannot trust it to a third party like that. It goes against everything we've been told about online security for past 5 years. Are you sure this is the only way?

**Comment by NightOwl888** [comment]
My bad. Apparently I don't need your assistance for this.

I went wrong by *providing* my password the first time around. When I did that, it failed to authenticate. I am not sure why. It even failed for one of my own repos that I created. So, I recreated it without providing a password and it magically worked (with my user name). Go figure.

Anyway, your name is now showing up as "assigned" instead of "pending" for security claims. You should now see the feed. **But there is no need for you to do anything with it now.**

Please don't press the build button as that will increment the build number and do a commit and label in all 5 repos. But basically the extent of the release process is to build, wait a few minutes for the build to complete, then push the feed upstream to NPM and NuGet. The CDN and bower are automatic once they are set up.

Actually, MyGet is the only CI service that allows you to sign up and work through to completion without getting the owner of the repo involved (assuming you are a collaborator). I am unable to setup TravisCI. And I looked at about 8 other services, all of them have the same issue - they need permission from the repo owner in order to be setup. This issue appears to be primarily a problem with GitHub's permissions.

**Comment by snikch** [comment]
Awesome, that's great news. Cool to have a proper CI setup all sorted - great stuff.

**Comment by NightOwl888** [comment]
FYI - I have left this open primarily because the release process has not been very stable. Pushing to NPM wasn't working correctly at first, then the README for NPM was failing. There is still [an intermittent issue](https://github.com/arturadib/shelljs/issues/206) with the build which I am awaiting an official release for. The issue causes the build to fail randomly, but trying again seems to work.

The steps outlined here (minus the unit testing and automated documentation) are now complete. There are [CONTRIBUTING.md](https://github.com/snikch/jquery.dirtyforms/blob/master/CONTRIBUTING.md) and [RELEASING.md](https://github.com/snikch/jquery.dirtyforms/blob/master/RELEASING.md) which outline the procedures.
