### ISSUE TITLE
tinyMCE helper dont run with newest tinyMCE versions

### ISSUE THREAD

**Issue by samuelsolis** [snikch/jquery.dirtyforms#74]
I'm using 4.0.21 version (2014-04-01) and the helper don't run correctly. I'm not sure the correct way for resolve it but I'm trying to do.

I'm think that the selectors aren't correctly and tiny has diferents classes right now. I'm not frontend developer and have some problems resolving this kinds of issues ... if somebody have the same problems please share your solutions for helping. 

Regards!

**Comment by NightOwl888** [comment]
@samuelsolis 

I did some more research and it seems that the new jQuery version of tinyMCE is initialized differently than the 3.x version. The main problem was that the 'advanced' theme option doesn't work anymore (as pointed out [here](http://www.tinymce.com/wiki.php/Tutorial:Migration_guide_from_3.x) the advanced theme has been removed). But, I found a configuration that works from [this StackOverflow answer](http://stackoverflow.com/questions/21434388/how-do-i-use-tinymce-jquery-package-and-what-is-the-difference-with-tinymce-jque#21453442).

The difference between this configuration and the 3.x demo I posted in #51 are as follows.

1. The `tinymce.min.js` file is included into the page just before the `jquery.tinymce.min.js` file as shown in the above StackOverflow answer.
2. The theme must be changed to `'modern'` 

So, in the demo you can change the entire initialization of tinyMCE to this and it will work with the latest 4.5.11 and presumably all prior 4.x versions.

```js
$('textarea.tinymce').tinymce({
	theme: 'modern'
});
```
It also works using the standard initialization code of tinyMCE, but in both cases you must include the `jquery.tinymce.min.js` file for it to interact with dirty forms.

```js
tinyMCE.init({        
	mode : "textareas",        
	theme : "modern"   //(n.b. no trailing comma, this will be critical as you experiment later)
});
```

When using the jQuery initialization code, you will need to ensure that the selectors are setup correctly. They work the same way that all jQuery selectors work, but for that you just need to reference the [jQuery selector documentation](https://api.jquery.com/category/selectors/).

Suffice to say there doesn't appear to be any problem at all with operating with tinyMCE 4.x as long as you initialize tinyMCE properly and include the `jquery.tinymce.min.js` file.

**Comment by samuelsolis** [comment]
Wow! @NightOwl888  really thanks for the fast help. The solution that you comment run correctly. Before this, I made a dirty solution that resolve my problem. 

Its a new helper but have a problem that I don't know how to resolve yet.  This code only run if the tinymce has defined with the name "tinymce". If this var exist and have a tinymce object (like my case), this code run.

Really is very simple, only select the differents editors and check if they're dirty or not using tinymce API. It's not very clean but I post it because it can be usefull for anybody.

```javascript
(function($){
	// Create a new object, with an isDirty method
	var dirtytinymce = {
		ignoreAnchorSelector : '.mceEditor a,.mceMenu a',
		isDirty : function(form){
			var isDirty = false;
			if (formHasTinyMCE(form)) {
				// We check all tinymce editors
          var edID = 0;
          for(edID in tinymce.editors){
            if (tinyMCE.editors[edID].isDirty()){
              isDirty = true;
              $.DirtyForms.dirtylog('tinyMCe is dirty');
              return true;
            }
          }
			}
			return isDirty;
		}
	}
	// Fix: tinymce throws an error if the selector doesn't match anything
	// (such as when there are no textareas on the current page)
	var formHasTinyMCE = function(form) {
		try {
      return jQuery.type(tinymce) === "object";
		}
		catch(e) {
			return false;
		}
	}
	// Push the new object onto the helpers array
  $.DirtyForms.helpers.push(dirtytinymce);

})(jQuery);
```

**Comment by NightOwl888** [comment]
Yea, now it makes more sense what you are saying. You needed the jQuery wrapper or the `:tinymce` selector won't work because that is where it is defined.

Thanks for the code for reference. It might make sense to do something like this so the jQuery wrapper of tinyMCE won't be required, because I have seen some comments that said that using tinyMCE with jQuery is much slower. But I haven't worked out a way to make this universal because the of the variable reference to the tinymce object. There is probably a way to pass in the variable name as an option when building dirty forms and then to reference it within the plugin, but that is a matter for more research.

**Comment by samuelsolis** [comment]
Yes, the code is similar, only work without the jquery wrapper. I don't know exactly the way of make this solution global, probably you're right and the tinymce object can be passed by reference... But I don't know, my javascript knowledge isn't very hight :)

Thank anyway for resolving my problem. In my opinion we can close this issue .

Regards!
