### ISSUE TITLE
I get both Facebox and Chrome dialog.

### ISSUE THREAD

**Issue by JunichiIto** [snikch/jquery.dirtyforms#75]
When I want to leave page by clicking link, I get both Facebox and Chrome dialog. No need to show twice. How can I fix it?

![amkrcp6v3y](https://cloud.githubusercontent.com/assets/1148320/8171025/c850f660-13ef-11e5-9326-da90efd67f8a.gif)

- Chrome: Version 43.0.2357.81 (64-bit)
- OS: Max OS X 10.10.3
- jQuery: 1.11.2
- dirtyforms: Downloaded a week ago

```html
<form class="dirtyform dirtylisten dirty" id="edit_session_72" enctype="multipart/form-data" action="/sessions/72" accept-charset="UTF-8" method="post">
```

```javascript
(function() {
  $(function() {
    $('.dirtyform').dirtyForms();
  });
}).call(this);
```

**Comment by NightOwl888** [comment]
I believe this is the same as #49. I created [a patch](https://github.com/snikch/jquery.dirtyforms/commit/26fdfec892ab479606693942a39f89f169fa611c) for it that will be in the next release, but in the meantime you can fix the script manually.

**Comment by JunichiIto** [comment]
Great, it worked for me. Thank you!
