### ISSUE TITLE
Element inside ignoreClass triggers popup

### ISSUE THREAD

**Issue by burmester** [snikch/jquery.dirtyforms#77]
When I have a anchor-link with my ignore-class and press the table inside the warning is still shown.
```html
<a href="#criteria" class="ignoreDirty">
Show me more
<table class="assessment-summary">
  <tbody>
   <tr>
    <td class="   "></td>
    <td class="   "></td>
    <td class="   "></td>
   </tr>
  </tbody>
 </table>
</a>
```

**Comment by NightOwl888** [comment]
The `ignoreClass` is currently only supported when it is applied directly to the element. You could work around this by using a selector to apply the class everywhere you need it, such as.

```javascript
$('assessment-summary input).addClass('ignoreDirty');
```

This is a good idea, though and I plan to add support for ignoring children in the next version.
