### ISSUE TITLE
Bootstrap modal Dialog Integration

### ISSUE THREAD

**Issue by GeorgeNarcis** [snikch/jquery.dirtyforms#78]
Hello,
 I am trying to integrate bootstrap modal as custom dialog to dirtyforms but I can't figure it out, has anyone tried it before or has an working example ?

**Comment by NightOwl888** [comment]
Thanks for pointing out that Bootstrap has its own modal. I am planning to release some pre-fabricated dialog plugins with the v2 release and after some experimenting here is what I came up with for Bootstrap 3. Let me know if you need customization over and above this so I can include the options to set the CSS classes on the dialog object (like `$.DirtyForms.dialog.cancelButtonText = 'No wait, don't go anywhere!'`).

```javascript
// Bootstrap modal dialog (for jQuery Dirty Forms)

// Support for UMD: https://github.com/umdjs/umd/blob/master/jqueryPluginCommonjs.js
// This allows for tools such as Browserify to compose the components together into a single HTTP request.
(function (factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['jquery'], factory);
    } else if (typeof exports === 'object') {
        // Node/CommonJS
        module.exports = factory(require('jquery'));
    } else {
        // Browser globals
        factory(jQuery);
    }
}(function ($) {
    // Create a local reference for simplicity
    var df = $.DirtyForms;
    var $dlg;

    $.DirtyForms.dialog = {
        // Custom properties and methods to allow overriding (may differ per dialog)
        continueButtonText: 'Leave This Page',
        cancelButtonText: 'Stay Here',

        // Typical Dirty Forms Properties and Methods
        fire: function (message, title) {
            var content = 
                '<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">' + 
                  '<div class="modal-dialog" role="document">' + 
                    '<div class="modal-content">' + 
                      '<div class="modal-header">' + 
                        '<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>' + 
                        '<h4 class="modal-title" id="exampleModalLabel">' + title + '</h4>' + 
                      '</div>' + 
                      '<div class="modal-body">' + message + '</div>' + 
                      '<div class="modal-footer">' +
                        '<button type="button" class="dirty-continue btn btn-default btn-primary" data-dismiss="modal">' + this.continueButtonText + '</button>' +
                        '<button type="button" class="dirty-cancel btn" data-dismiss="modal">' + this.cancelButtonText + '</button>' + 
                      '</div>' + 
                    '</div>' + 
                  '</div>' + 
                '</div>';

            $dlg = $(content);
            $('body').append($dlg);
            $dlg.modal({ show: true });
        },
        bind: function () {
            $('.dirty-continue').click(function (e) {
                df.choiceContinue = true;
            });
            $dlg.bind('hidden.bs.modal', function (e) {
                df.choiceCommit(e);
            });
        },

        // Stashing (needed only if you have a form inside a modal dialog
        // as Bootstrap modal does not support stacking modal dialogs).
        stash: function () {
            return false;
        },
        refire: function () {
            return false;
        },

        // Selector for stashing the content of another dialog.
        selector: 'no-op',
    };

}));

```

There is also a [pNotify modal](https://github.com/NightOwl888/jquery.dirtyforms/blob/vnext/dialogs/pnotify.js) that can use the Bootstrap themes.

**Comment by NightOwl888** [comment]
FYI - note my edit. The original code I posted had a memory leak (it kept adding divs to the body without cleaning them up afterward).

I will also work out how to do stashing and post that version as well.

**Comment by NightOwl888** [comment]
Hmm...there doesn't seem to be any issue with stacking modal dialogs as the documentation would indicate. So the above looks like it will cover every use case.

**Comment by GeorgeNarcis** [comment]
Thank you for this example, it would be nice to customize everything that is presented to the user.

 I was wondering if it wouldn't be easier to have the modal dialog already created from outside and only specify id to the dirtyforms plugin(possibly some predefined classes for continue/cancel buttons), but i am not familiar with the inner works of the plugin so I'm sorry if I am saying something wrong.

**Comment by GeorgeNarcis** [comment]
Your example worked, I successfully integrated bootstrap dialog with a modal declared outside in my html file, in that way i was able to control the translation and customize the messages in the dialog.

**Comment by NightOwl888** [comment]
Thanks for the feedback. I have been considering this request seriously, and I am inclined to do it because the design of Bootstrap requires you to have lots of control over the HTML attributes on the page.

Basically, it means that there will need to be a full set of properties for each of the following:

1. The ID of the dialog.
2. The title.
3. The message.
4. The class of the continue button.
5. The continue button text.
6. The cancel button text.

And the logic will be set up to replace each of the text portions of the dialog as needed inside of the fire method, and hook and unhook the continue button event as needed.

What you said about translation makes me wonder if you are setting the properties in JavaScript the way you should. Note that the browser dialog (when you try to navigate away with the back button or changing the URL) will use the `$.DirtyForms.message`, so it is important that it is translated as well. Firefox doesn't show the message, but other browsers do. So, it would be best to set it in JavaScript to the right language rather than having to set it in 2 different places (once in JavaScript for the browser and once on the HTML form).

**Comment by GeorgeNarcis** [comment]
The app I am working on  (quite big app) has its own translation logic , so I have to control this. Regarding the problem when you press back button or reload page I have noticed that the default browser dialog is displayed instead of the custom declared one.

Is there any way I can overcome this , or this is not even related to the plugin ?

**Comment by NightOwl888** [comment]
Dirty Forms uses the browser dialog as a fallback because the only way to detect page exits that are not initiated on the page (such as the back button) is to attach to the [beforeunload event](https://developer.mozilla.org/en-US/docs/Web/Events/beforeunload). We use the same message whether sending to the browser or to the JavaScript dialog, so it is maintained in 1 place.

So, you will need to ensure the message property is set to the right language. Unfortunately, I can't think of a reasonable solution that doesn't involve adding JavaScript to the page.

```javascript
<script>
$(function() {
    $.DirtyForms.message = 'Some translated text';
});
</script>
```

**Comment by NightOwl888** [comment]
Do note that the other properties such as title or the button text don't have anything to do with the browser, though. `$.DirtyForms.message` is the only one.

**Comment by GeorgeNarcis** [comment]
So if I understand correctly, when I press back button / reload page I can only control the message property ? I have noticed that all the dialog including appearance / layout uses the browser default dialog and my bootstrap modal is ignored.

**Comment by NightOwl888** [comment]
That is correct. Dirty Forms only shows the nice user-friendly dialog when clicking on links that redirect to other pages. But any actions that would exit using the browser show the browser's dialog, in which case Dirty Forms supplies the message for it via JavaScript.

**Comment by GeorgeNarcis** [comment]
Ok, thank you.

**Comment by NightOwl888** [comment]
BTW - I thought of a better approach to maintaining the localized text than what I prescribed before. 

```javascript
$.DirtyForms.message = $('#messageid').text();
```

Then you don't have to put the JavaScript into the HTML page. You also need to use the `.html()` or `.val()` method as appropriate depending on what type of element has the translated message text.

**Comment by NightOwl888** [comment]
FYI - the [Bootstrap Modal Dialog Module](https://github.com/NightOwl888/jquery.dirtyforms.dialogs.bootstrap.dist) is now in pre-release, and it is compatible with Dirty Forms (>=1.0.0).

If you get a chance to try it out (and/or the 2.0 BETA of Dirty Forms), please report back any issues you find. Thanks.
