### ISSUE TITLE
Not work with pjax

### ISSUE THREAD

**Issue by fmh** [snikch/jquery.dirtyforms#81]
I use pjax to navigate between menus, the dirtyforms work fine with form with window load or close window, but when navigate using pjax, i can switch without receive alert.

**Comment by NightOwl888** [comment]
Thanks for the report. Can you provide the code to reproduce the issue? A [jsFiddle](https://jsfiddle.net/) example will do.

**Comment by fmh** [comment]
http://jsfiddle.net/0r1oo1ps/

**Comment by NightOwl888** [comment]
Your example works fine, but you are linking to the raw GitHub page at `https://raw.githubusercontent.com/NightOwl888/jquery.dirtyforms.dist/master/jquery.dirtyforms.min.js` which does not include the correct mime type for JavaScript, so the browser is interpreting it as a plain text file. 

You can instead use the CDN:

```
//cdn.jsdelivr.net/jquery.dirtyforms/1.2.3/jquery.dirtyforms.min.js (latest stable)

//cdn.jsdelivr.net/jquery.dirtyforms/2.0.0-beta00004/jquery.dirtyforms.min.js (latest beta)
```

Alternatively, you can use one of the [package managers](https://github.com/snikch/jquery.dirtyforms#package-managers)  to host the code locally.

**Comment by NightOwl888** [comment]
See the updated example: http://jsfiddle.net/0r1oo1ps/5/

**Comment by fmh** [comment]
it still not work in my prod app.
I can solve my issue by testing if my form is dirty like this: 
`````
$(document).on 'pjax:beforeSend', (event) ->
  if $('form').dirtyForms(('isDirty'))
     #// call my dirtyform alert , but how do it 
```
how call (trigger) the dirtyform original alert ?
thx.

**Comment by NightOwl888** [comment]
In this case, you can [customize the event binding](https://github.com/snikch/jquery.dirtyforms#event-handler-customization) to simulate an anchor click. One option is just to add an event you can trigger to fire the form check.

```javascript
	$(document).bind('bind.dirtyforms', function (ev, events) {
		var originalBind = events.bind;
		
		events.bind = function (e) {
			$(document).on('checkdirty.dirtyforms', events.onAnchorClick);
			originalBind(e);
		};
	});
	
	// Make sure to call the above before calling dirtyForms.
	$('form').dirtyForms();
```

And then you can use it like this.

```javascript
	$(document).on 'pjax:beforeSend', (event) ->
		$(document).trigger('checkdirty.dirtyforms');
```

It may also work in your case to just attach the pjax event directly to the `events.onAnchorClick` event handler.

```javascript
	$(document).bind('bind.dirtyforms', function (ev, events) {
		var originalBind = events.bind;
		
		events.bind = function (e) {
			$(document).on('pjax:beforeSend', events.onAnchorClick);
			originalBind(e);
		};
	});
	
	// Make sure to call the above before calling dirtyForms.
	$('form').dirtyForms();
```

**Comment by fmh** [comment]
thx, but this have no effect on my case :( 

````js


$(document).bind 'bind.dirtyforms', (ev, events) ->
  originalBind = events.bind

  events.bind = (e) ->
    $(document).on 'checkdirty.dirtyforms', events.onAnchorClick
    originalBind e
    return
  return

$(document).on 'pjax:beforeSend', (event) ->
  if $('form').dirtyForms(('isDirty'))
   alert("my alert !!!") /// this is work.
    $(document).trigger('checkdirty.dirtyforms') // want show alert with choice but nothing
    return false // must stop send pjax request if form is dirty

// this my original call to pjax 

$(document).on 'click', '.pjax', (event) ->
  if event.which > 1 || event.metaKey || event.ctrlKey
    return
  else if $.support.pjax
    event.preventDefault()
    $.pjax
      container: $(this).data('pjax-container') || '[data-pjax-container]'
      url: $(this).data('href') || $(this).attr('href')
      timeout: 2000
  else if $(this).data('href')
    window.location = $(this).data('href')

**Comment by fmh** [comment]
it wooorks 😄 , with events.onRefireClick or events.onRefireAnchorClick
thx 👍

**Comment by fmh** [comment]
sorry, but it work once, if I click again on a link that goes directly on the page without confirmation

**Comment by NightOwl888** [comment]
@fmh 

The default behavior has changed in [2.0.0-beta00005](https://github.com/snikch/jquery.dirtyforms/releases/tag/2.0.0-beta00005) to include links with no HREF tag by default. That should fix this so you don't need to attach the event. However, depending on what libraries you are using, you may need to add an `ignoreSelector` to Dirty Forms to stop watching them.

```js
$('form').dirtyForms({ ignoreSelector: 'a.some-class:not([href])' });
```

I am closing this issue for now, but feel free to reopen it if you are still having problems with PJax.
