### ISSUE TITLE
No public method to get original value from field

### ISSUE THREAD

**Issue by ar4ers** [snikch/jquery.dirtyforms#83]
The only way to achieve this goal is to use `$('#input').data('df-orig'); `
It will be more durable(to internal changes) and convenient to have some public method from `dirtyforms` itself, for ex. something like `$('#form').dirtyForms('getOriginal', '#field');`

**Comment by NightOwl888** [comment]
Thanks for the suggestion.

While I am trying to make Dirty Forms as flexible as possible, I am also keeping a close guard on the feature set to keep unnecessary bloat out of the design and to keep the download size small.

I am not sure there is much real-world use for getting the original value from Dirty Forms and it is really not intended to be part of the public API. However, as you have already discovered, there is a simple way to get the value if you really need to. But adding another 100 or so bytes to the code for such a thing is probably not a good tradeoff for the amount of value it provides.
