### ISSUE TITLE
Listening to html 5 input types

### ISSUE THREAD

**Issue by KalleJohansson** [snikch/jquery.dirtyforms#88]
Hi, it could very well be just me..
Anyway i just discovered that it seems as dirtyforms (by default) does no add an input of type search to listen to while setting a form as dirty. 
In this case my input was type="search", and it was ignored (not added for listening), however when i changed to type="text", the input was added for listening. 
I haven't found anything in the docs, that says anything about disallowed input types, or for that matter customizing (that is adding input types to listen for in a form).

**Comment by NightOwl888** [comment]
One of the configurable [options](https://github.com/snikch/jquery.dirtyforms#user-content-options) is `fieldSelector`, which allows you to change the selector of fields being listened to.

The default value is

```
 input:not([type='button'],[type='image'],[type='submit'],[type='reset'],[type='file'],[type='search']),select,textarea
```

As you can see, search is excluded by default. You can include it changing the selector to

```
 input:not([type='button'],[type='image'],[type='submit'],[type='reset'],[type='file']),select,textarea
```

A search field is not typically persisted to durable storage, so the default behavior is to exclude it from dirty checking.

**Comment by KalleJohansson** [comment]
Hi, 
and thanks for the quick answer, i guess i should RTFM ;)
