### ISSUE TITLE
Ignoring Things Writeup

### ISSUE THREAD

**Issue by jdtemple** [snikch/jquery.dirtyforms#92]
Your writeup states that the default class for ignoring things is "dirtyignore". After a little investigating, I found that it's actually "ignoredirty".

**Comment by NightOwl888** [comment]
In version 1.x the default value is `ignoredirty`, but this was changed in version 2.x to `dirtyignore` to be consistent with the other classes. See number 9 under [breaking changes](https://github.com/snikch/jquery.dirtyforms/releases/tag/2.0.0-beta00003).

If you have version 1.x, you should refer to the [documentation for 1.x](https://github.com/snikch/jquery.dirtyforms/tree/8e731503db5fe95a70700cf81295e5c7334fa253#readme), not the documentation on the master branch, which is for the 2.x version.

**Comment by jdtemple** [comment]
Oops! My fault. I grabbed the package via nuget yesterday.  I didn't look too closely at the version.
