### ISSUE TITLE
Bootstrap dialog is not applied when refreshing the page or close the tab

### ISSUE THREAD

**Issue by sky3913** [snikch/jquery.dirtyforms#95]
I've installed the Bootstrap Modal dialog for JQuery Dirty Forms using nuget. I bundled this package into the `BundleConfig` class

```
bundles.Add(new ScriptBundle("~/bundles/dirtyforms").Include(
	"~/Scripts/jquery.dirtyforms.js",
	"~/Scripts/jquery.dirtyforms.dialogs.bootstrap.js"));
```

and initialize the Dirty Forms in the page `$('form').dirtyForms();`.

It works when I try to redirect to another page if there is any changes, but if I click the refresh button on the browser or closed the tab, the bootstrap modal is not applied. Is there any configuration that I've missed or does it only apply on the redirecting page?

**Comment by Alex-1984** [comment]
It seems that this is the default behavior of the bootstrap modal plugin.

See https://github.com/NightOwl888/jquery.dirtyforms.dialogs.bootstrap.dist#readme under "Purpose" =>

> This module causes Dirty Forms to use Bootstrap Modal as its dialog when the user attempts to leave the page by clicking a hyperlink (but not when interacting with the navigation buttons of the browser).

**Comment by sky3913** [comment]
Thank you for the information

**Comment by NightOwl888** [comment]
Alex-1984 is correct, this behavior is by design. Browsers that support `onbeforeunload` do not allow overriding its behavior, so there is no way to show a custom dialog in that case. The custom dialog is just to provide a better user experience when the user clicks a link within the page to navigate away.
