### ISSUE TITLE
Dist subfolders are empty

### ISSUE THREAD

**Issue by adm-husker** [snikch/jquery.dirtyforms#97]
Hi,

When i download the last release (2.0.0) zipped or i download it via composer (PHP) all the directories under dist directory are empty.

Is there a workaround ?

**Comment by NightOwl888** [comment]
There are [many ways to get Dirty Forms](https://github.com/snikch/jquery.dirtyforms#download--installation) including package managers and via CDN. Both [Bower](http://bower.io/) and [NPM](https://www.npmjs.com/) are platform independent (based on node.js) and therefore could be used with PHP.

There is currently no official composer support ([contributions](https://github.com/snikch/jquery.dirtyforms/blob/master/CONTRIBUTING.md) welcome). 

For [supporting Bower, we had to break up the project into a development repo and several distribution repos](https://github.com/bower/bower/issues/24). This repository is for development only. The official distribution repo for the `jquery.dirtyforms` component is at https://github.com/NightOwl888/jquery.dirtyforms.dist.

The all of the distribution repositories are Git submodules of this project. By default the dist folder is empty, but you could get them by running the following Git command after cloning the repository to your system:

```
git submodule update --init
```
See [this article](https://chrisjean.com/git-submodules-adding-using-removing-and-updating/) for assistance with Git submodule commands.

Do note that you don't necessarily need to update the submodules to [make a contribution](https://github.com/snikch/jquery.dirtyforms/blob/master/CONTRIBUTING.md), that is, just doing a clone and then adding to the source is enough.
