### ISSUE TITLE
Always get the dialog

### ISSUE THREAD

**Issue by wesleywesley** [snikch/jquery.dirtyforms#98]
I'm always getting the dialog yet as far as I know i have no dirty fields..

I bound    

```
$(document).bind("dirty.dirtyforms ", function(e) {
    alert("dirty");
  });

```
to see if there were any, and I did not get such an alert (when I made no changes to the form). However, I did get the onbeforeunload alert saying that i must save the form first. 

How can I see which fields are (supposedly) dirty? 

I suspect this may have something to do with ckeditor, I added your helper plugin..

**Comment by NightOwl888** [comment]
> How can I see which fields are (supposedly) dirty? 

The easiest way is to use CSS to style the dirty fields with a background color, such as

```html
<style type="text/css">
    input.dirty, input.dirty + label, select.dirty, textarea.dirty {
        background-color: red;
    }
</style>
```
> **Note:** You will need to change the above from `.dirty` to a different name if you changed the name of the `dirtyClass` setting.

Or you can use the developer tools in your browser to get a live view of the HTML so you can see which CSS classes are applied to your inputs. Any field that is dirty will have the value of the `dirtyClass` (with the default of `dirty`).

Of course, that will only tell you whether any standard HTML fields are dirty. You can check the entire page at once using

```js
alert($('form').dirtyForms('isDirty'));
```

Then to narrow it down, use a more specific selector than `form`.

Each custom widget (including CKEditor) uses its own scheme to tell whether it is dirty/clean. You can use a selector to narrow the `isDirty` function to a specific area so you can narrow down what might be dirty. So, you should use a container div that the CKEditor is in to determine if one of them is returning dirty.

```html
<div class="ckeditor-container">
	<textarea name="editor1" id="editor1" rows="10" cols="80">
		This is my textarea to be replaced with CKEditor 1.
	</textarea>
</div>

<script>
	//// Replace the <textarea id="editor1"> with a CKEditor
	//// instance, using default configuration.
	CKEDITOR.replace('editor1');
</script>
```

```js
alert($('div.ckeditor-container').dirtyForms('isDirty'));
```

However, if none of your fields are dirty, you probably have a misconfiguration or a conflict of some sort. It is also possible that there is a version of CKEditor that the [CKEditor helper module](https://github.com/NightOwl888/jquery.dirtyforms.helpers.ckeditor.dist#readme) does not support. So if you provide an example that exhibits the problem as well as the version of CKEditor you are using and how it is configured that would be helpful.

A [JSFiddle](https://jsfiddle.net/) or a standalone HTML document with a demo posted here will do nicely.

**Comment by wesleywesley** [comment]
```
alert($('form').dirtyForms('isDirty')); -> true;
$(".dirty").length however returns 0.
```

So this seems to be conflicting somehow, both tell a different story..
Is there anything else I can look for? It is related to ckeditor, when I disable the editor everything works fine.

**Comment by wesleywesley** [comment]
Well seems like this has nothing to do with you but with the plugin. Need to contact them instead as checkDirty() in CKEDITOR returns true after initialization of their spellcheck. Thanks for fast response!
