### ISSUE TITLE
Bootstrap dialog

### ISSUE THREAD

**Issue by OlivierGrimard** [snikch/jquery.dirtyforms#99]
I just tried to add the Bootstrap Module using dirtyForm 2.0.0 and was unable to display the Bootstrap popup by reloading the page. 

See the example here: https://jsfiddle.net/DTcHh/17974/

The pjax link works but if you try to reload the page, the bootstrap module is not working. 
Please let me know if someone has an idea how to fix this.
Thank you.

**Comment by NightOwl888** [comment]
As pointed out in [the documentation](https://github.com/NightOwl888/jquery.dirtyforms.dialogs.bootstrap.dist#purpose), the dialog only works when clicking links within the page. Browsers do not provide a way to override their default dialog, so when interacting with the browser navigation, you will get the browser default dialog (provided the dialog supports `beforeunload` - not all of them do).

I would fix it if I could, but there is no workaround for this.
